elasticsearch522-master:
    image: elasticsearch:5.2.2
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: group=elasticsearch
elasticsearch522-base:
  image: elasticsearch:5.2.2
  hostname: es-master
  environment:
    ES_JAVA_OPTS: -Xms3g -Xmx3g
  stdin_open: true
  tty: true
  links:
    - elasticsearch522-node:elasticsearch
  command:
    - /docker-entrypoint.sh
    - -Ecluster.name=Elasticsearch5
    - -Ediscovery.zen.ping.unicast.hosts=elasticsearch
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: group=elasticsearch
elasticsearch522-node:
  image: elasticsearch:5.2.2
  hostname: es-master
  environment:
    ES_JAVA_OPTS: -Xms3g -Xmx3g
  stdin_open: true
  tty: true
  links:
    - elasticsearch522-master:elasticsearch
  command:
    - /docker-entrypoint.sh
    - -Ecluster.name=Elasticsearch5
    - -Ediscovery.zen.ping.unicast.hosts=elasticsearch
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: group=elasticsearch
