.catalog:
  name: "Elasticsearch"
  version: "5.2.2"
  description: "Elasticsearch. You know, for search"
  uuid: # Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: # The minimum version of Rancher that supports the template
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
elasticsearch522-master:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
  scale: 1
elasticsearch522-node:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
  scale: 2
